nodeLinker: node-modules
enableGlobalCache: false
enableTelemetry: false
compressionLevel: mixed
enableImmutableInstalls: false
enableInlineBuilds: true
enableScripts: false

supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64